-- Notifications schema for مساعد المعلم
-- Run this in Supabase SQL Editor.

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  account_code text not null,
  student_code text not null,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists push_subscriptions_account_idx
  on public.push_subscriptions(account_code);

create index if not exists push_subscriptions_student_idx
  on public.push_subscriptions(student_code);

alter table public.push_subscriptions enable row level security;

-- The Worker uses the Supabase service-role key, so browser clients do not need
-- direct write access to this table.
revoke all on public.push_subscriptions from anon, authenticated;

-- Public student publishing expected by index.html:
-- The existing app calls:
--   rpc('publish_student_public', { p_row: <json object> })
-- and the student page reads from public.student_public by student_code.
--
-- If these objects already exist in your Supabase project, do not recreate them.
-- This file only creates the notification subscription table.
